[package]
name = "hello_world"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.2"
itertools = "0.8.0"
